// REPLACE: Update with your real project data
export const projects = [
  {
    slug: 'mehta-residence',
    title: 'The Mehta Residence',
    location: 'South Delhi',
    category: 'Luxury Residential',
    year: '2024',
    area: '4,200 sq ft',
    description: 'A serene four-bedroom home where materiality does the talking. Raw plaster walls, book-matched marble, and warm oak joinery create a palette that is both grounded and elevated — a home that feels ancient and entirely new at once.',
    tags: ['Residential', 'Full Design', 'Supervision'],
  },
  {
    slug: 'arora-penthouse',
    title: 'The Arora Penthouse',
    location: 'Gurugram',
    category: 'Luxury Residential',
    year: '2024',
    area: '6,800 sq ft',
    description: 'Designed for a couple with a deep appreciation for contemporary art, this penthouse blends gallery-like restraint with the warmth of a lived-in home. Double-height ceilings frame the sky. Stone, linen, and bronze move through the space as a quiet, considered vocabulary.',
    tags: ['Residential', 'Full Design', 'Art Integration'],
  },
  {
    slug: 'rooh-restaurant',
    title: 'Rooh — A Modern Dining Experience',
    location: 'New Delhi',
    category: 'Restaurant & F&B',
    year: '2023',
    area: '3,100 sq ft',
    description: 'An immersive dining environment built around candlelight, acoustic texture, and layered materiality — designed to feel intimate even at 100 covers. Rough-sawn timber, burnished plaster, and deep charcoal stone deliver a space that recedes and lets food take centre stage.',
    tags: ['F&B', 'Commercial', 'Full Design'],
  },
  {
    slug: 'sharma-villa',
    title: 'The Sharma Villa',
    location: 'Noida',
    category: 'Luxury Residential',
    year: '2023',
    area: '8,500 sq ft',
    description: 'A sprawling family home where every room has its own identity while remaining in quiet conversation with the rest — unified by a palette of warm neutrals, aged brass, and honed stone. Designed to accommodate three generations without compromise.',
    tags: ['Residential', 'Full Design', 'Multi-generational'],
  },
  {
    slug: 'kapoor-apartment',
    title: 'The Kapoor Apartment',
    location: 'South Delhi',
    category: 'Luxury Residential',
    year: '2023',
    area: '2,800 sq ft',
    description: 'A compact but considered apartment that proves restraint is not limitation. Every cubic foot is deliberate — storage concealed, light maximised, and materiality handled with the same care one would give a much larger space.',
    tags: ['Residential', 'Full Design'],
  },
  {
    slug: 'the-den-cafe',
    title: 'The Den — Concept Café',
    location: 'New Delhi',
    category: 'Café & F&B',
    year: '2022',
    area: '1,400 sq ft',
    description: 'A neighbourhood café designed as a retreat — wabi-sabi plaster, reclaimed oak, linen curtains, and the kind of light that makes you want to stay. The brief was simple: design a place where time moves differently.',
    tags: ['F&B', 'Concept', 'Branding Integration'],
  },
]
